apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgc-api
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgc-api
  template:
    metadata:
      labels:
        app: bgc-api
    spec:
      containers:
        - name: api
          image: bgc/bgc-api:dev-20250823005841
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              value: pg-postgresql.data.svc.cluster.local
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGSSLMODE
              value: disable
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-postgresql
                  key: postgres-password
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bgc-api
  namespace: data
spec:
  selector:
    app: bgc-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
