apiVersion: batch/v1
kind: Job
metadata:
  name: bgc-migrate-0001
  namespace: data
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: docker.io/bitnami/postgresql:17.6.0-debian-12-r0
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-postgresql
                  key: postgres-password
          volumeMounts:
            - name: migrations
              mountPath: /migrations
          command:
            - /opt/bitnami/scripts/postgresql/entrypoint.sh
            - /bin/bash
            - -lc
            - /opt/bitnami/postgresql/bin/psql -h pg-postgresql -U postgres -d postgres -p 5432 -f /migrations/0001_init.sql
      volumes:
        - name: migrations
          configMap:
            name: bgc-migration-0001
            items:
              - key: 0001_init.sql
                path: 0001_init.sql
