apiVersion: batch/v1
kind: Job
metadata:
  name: bgc-mviews-add-uniq
  namespace: data
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: sql
          configMap:
            name: bgc-mviews-add-uniq
      containers:
        - name: psql
          image: postgres:16
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-postgresql
                  key: postgres-password
          command: ["psql"]
          args:
            - -h
            - pg-postgresql
            - -U
            - postgres
            - -d
            - postgres
            - -p
            - "5432"
            - -v
            - ON_ERROR_STOP=1
            - -f
            - /sql/uniq.sql
          volumeMounts:
            - name: sql
              mountPath: /sql
              readOnly: true
