apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgc-api
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgc-api
  template:
    metadata:
      labels:
        app: bgc-api
    spec:
      containers:
        - name: api
          image: bgc/bgc-api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: pg-postgresql.data.svc.cluster.local
            - name: DB_USER
              value: bgc
            - name: DB_NAME
              value: bgc
            - name: DB_PORT
              value: "5432"
            - name: PGSSLMODE
              value: disable
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-postgresql
                  key: postgres-password
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bgc-api
  namespace: data
spec:
  selector:
    app: bgc-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080

